name: Send Notifications

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Call Notification API
        run: |
          curl -sSf https://mosk-staden-perstorp.vercel.app/api/scheduled-notifications